version: "3"
services:
  db:
    image: jijiwon/goyo-sql
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: goyo-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=goyo-mog-db
      - MYSQL_ROOT_PASSWORD=wldnjs@0329
      - TZ=Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: jijiwon/goyo-spring
    depends_on:
      - db
    container_name: goyo-spring-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/goyo-mog-db?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: wldnjs@0329

volumes:
  mysql-data:
    driver: local